name: Android Debug Build & Release with Auto-Increment

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git operations

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get commit count and set version info
        id: get_version_info
        run: |
          # Get the number of commits to use as the build number
          BUILD_NUMBER=$(git rev-list --count HEAD)
          
          # Read the current version name from build.gradle.kts
          VERSION_NAME=$(grep "versionName" app/build.gradle.kts | cut -d'"' -f2)
          
          # Set environment variables for next steps
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Rename debug APK file
        run: |
          mkdir -p temp_output
          mv app/build/outputs/apk/debug/app-debug.apk temp_output/CashQR-v${{ env.VERSION_NAME }}+${{ env.VERSION_CODE }}-debug.apk

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: temp_output/CashQR-v${{ env.VERSION_NAME }}+${{ env.BUILD_NUMBER }}-debug.apk
          name: CashQR v${{ env.VERSION_NAME }} (Debug)
          tag_name: v${{ env.VERSION_NAME }}+${{ env.BUILD_NUMBER }}
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
